version: 1.0.0-alpha{build}
os: Visual Studio 2015 RC
branches:
  only:
  - master
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
configuration: Release
before_build:
  - nuget restore
build:
  project: Swift.Extensibility.sln
after_test:
- ps: .\NuGet\Create-Package.ps1
artifacts:
- path: '**\Swift.Extensibility.dll'
  name: Swift.Extensibility.dll
- path: '**\*.nupkg'
#deploy:
#  provider: NuGet
#  api_key:
#    secure: 3VAcdRzB2F5zv0BsV4Z+o31z5ZuiBWxmvz48/bIcV7/Zg74BiCMpqy9Iwdlm7BhS
#  artifact: /.*\.nupkg/